// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	sdk "microservice-assignment/sdk"

	mock "github.com/stretchr/testify/mock"

	shared "microservice-assignment/shared"
)

// MovieUseCase is an autogenerated mock type for the MovieUseCase type
type MovieUseCase struct {
	mock.Mock
}

// GetAllUseCase provides a mock function with given fields: param
func (_m *MovieUseCase) GetAllUseCase(param sdk.Param) <-chan shared.CommonResult {
	ret := _m.Called(param)

	var r0 <-chan shared.CommonResult
	if rf, ok := ret.Get(0).(func(sdk.Param) <-chan shared.CommonResult); ok {
		r0 = rf(param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan shared.CommonResult)
		}
	}

	return r0
}

// GetDetailUseCase provides a mock function with given fields: movieID
func (_m *MovieUseCase) GetDetailUseCase(movieID string) <-chan shared.CommonResult {
	ret := _m.Called(movieID)

	var r0 <-chan shared.CommonResult
	if rf, ok := ret.Get(0).(func(string) <-chan shared.CommonResult); ok {
		r0 = rf(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan shared.CommonResult)
		}
	}

	return r0
}
