// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	model "microservice-assignment/src/movie/v1/model"

	mock "github.com/stretchr/testify/mock"

	shared "microservice-assignment/shared"
)

// MovieRepository is an autogenerated mock type for the MovieRepository type
type MovieRepository struct {
	mock.Mock
}

// SaveLog provides a mock function with given fields: req
func (_m *MovieRepository) SaveLog(req *model.LogsRequest) <-chan shared.CommonResult {
	ret := _m.Called(req)

	var r0 <-chan shared.CommonResult
	if rf, ok := ret.Get(0).(func(*model.LogsRequest) <-chan shared.CommonResult); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan shared.CommonResult)
		}
	}

	return r0
}
