// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	sdk "microservice-assignment/sdk"

	mock "github.com/stretchr/testify/mock"

	shared "microservice-assignment/shared"
)

// OMDB is an autogenerated mock type for the OMDB type
type OMDB struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: param
func (_m *OMDB) GetAll(param sdk.Param) <-chan shared.CommonResult {
	ret := _m.Called(param)

	var r0 <-chan shared.CommonResult
	if rf, ok := ret.Get(0).(func(sdk.Param) <-chan shared.CommonResult); ok {
		r0 = rf(param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan shared.CommonResult)
		}
	}

	return r0
}

// GetDetail provides a mock function with given fields: id
func (_m *OMDB) GetDetail(id string) <-chan shared.CommonResult {
	ret := _m.Called(id)

	var r0 <-chan shared.CommonResult
	if rf, ok := ret.Get(0).(func(string) <-chan shared.CommonResult); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan shared.CommonResult)
		}
	}

	return r0
}
